version: '3.7'

services:

  front-angular:
    container_name: front-angular
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'